### ISSUE TITLE
Server error 

### ISSUE THREAD

**Issue by Maha-Rajan** [Leonidius20/BeatInspector#2] opened 2024-02-01 05:56 UTC
Logging in with Spotify was successful and the search query returned with the results but when I click on the song. It just shows server error.

**Comment by Leonidius20** [comment] 2024-02-01 15:22
Thank you for reporting this issue!

I've created a new release, version 0.0.2, which displays more descriptive error messages. Could you please download the new version (from the Releases section here on GitHub or from IzzyOnDroid when it becomes available there), make a screenshot of the error that is displayed when you click on a song, and attach it here?

**Comment by Maha-Rajan** [comment] 2024-02-01 16:53
The updated version does seem to provide better description of the error but now the search query doesn't seem to provide any results too. The previous version provide the results and only on clicking the song name there was an error.![Screenshot_20240201-222126_BeatInspector.png](https://github.com/Leonidius20/BeatInspector/assets/40870763/36047a2c-022b-4043-8d3e-c21fa4d28472)

**Comment by Leonidius20** [comment] 2024-02-02 07:56
It seems that this issue is caused by the fact that the Spotify API key I'm using is in "development" mode, which, as I've now realized, requires each user to be manually approved in the developer console. I will submit a request to Spotify to switch to production mode and this should solve the issue. I'll keep you updated on the progress. Sorry for the inconvenience.

**Comment by Maha-Rajan** [comment] 2024-02-02 11:59
Hi Leonidius20,

No inconvenience at all. I'm glad that you're doing an open source project
like this and I'm happy to help out in any way I can.

Thanks,
Maharajan

**Comment by Hamster45105** [comment] 2024-03-04 05:19
Hi! Would it be possible to allow users to  use their own key?

That way, people would be able to use the app even if your key stops working.

**Comment by Leonidius20** [comment] 2024-03-04 17:41
> Hi! Would it be possible to allow users to use their own key?
> 
> That way, people would be able to use the app even if your key stops working.

Hi @Hamster45105,
yes, i considered such a solution and will implement it if the quota extension request is denied by Spotify. I have submitted the request on March 1 after getting the app to comply with Spotify policies. For now, I don't want to add such a capability, because that would (likely) be in violation of Spotify terms and will lead to the quota extension request being denied. However, if it's denied for some other fundamentally unfixable reason (i.e. Spotify won't approve of concept of this app itself), then there will be no other way.

**Comment by Leonidius20** [comment] 2024-06-03 14:11
Hi @Maha-Rajan,
The quota extension has just been approved by Spotify. Could you check if the issue is solved? 
(you may want to update the app to the latest version, even though it should be working now on older versions too)

**Comment by Maha-Rajan** [comment] 2024-06-05 16:17
Thank you for your dedication. It works flawlessly now... 
One thing I wanted to point out is that the data being displayed has a low contrast value with some album art colours. 
![Uploading Screenshot_20240605-214456.png…]()

**Comment by Leonidius20** [comment] 2024-06-05 19:23
@Maha-Rajan 
could you please reattach the screenshot with the low contrast issue? looks like it didn't finish uploading

i will see if there's anything that can be done about the contrast

**Comment by Maha-Rajan** [comment] 2024-06-05 20:46
![Screenshot_20240605-214512](https://github.com/Leonidius20/BeatInspector/assets/40870763/b5d55893-e89c-4467-a7ee-b5296fac3ec6)

This has been the case for album art with lighter colors

**Comment by Leonidius20** [comment] 2024-06-06 17:21
@Maha-Rajan 
i have made changes to the colors in dark mode. They will be included in the next version of the app (i hope to release it in a week or two)

![Screenshot_20240606-201945](https://github.com/Leonidius20/BeatInspector/assets/25536411/669cee94-6b46-4d0d-8777-c3e80a2b8cc7)

**Comment by Leonidius20** [comment] 2024-06-16 14:12
version 0.0.7 with color fixes was released.

**Closed by Leonidius20** 2024-06-16 14:12 UTC
